### PR TITLE
implementing ifdraft package

### LINKED ISSUE #2086: ifdraft.sty support
MWE:

```latex
\documentclass{article}
\usepackage{ifdraft}
\begin{document}
\ifdraft{a}{b}
\end{document}
```

LaTeX output:

> b

LaTeXML output:
> Error:undefined:\ifdraft

### PR DESCRIPTION
**Pull request by teepeemm**
This completely implements the ifdraft package, which resolves #2086.

### CODE REVIEW

**Comment by dginev** [comment]
@teepeemm do you know what happened to the MANIFEST here?

**Comment by teepeemm** [comment]
I ran `make manifest`.  It told me that it added the one entry.  Github showed me the rest.  Should I revert that and manually add the one entry?

**Comment by dginev** [comment]
I think adding one line by hand will make this easier to merge, sure.

The MANIFEST has been manually curated for some time, if I remember correctly.

**Review by dginev — APPROVED** [review]
I see you went to the trouble of redoing the same TeX logic through the Perl binding layer. Neat exercise.

This looks good to merge to me now, thanks!

**Comment by brucemiller** [comment]
Sorry about the annoying manually sorted MANIFEST --- but it's easier to read that way!

Thanks for the binding; looks good!!

**Pull request merged**
