### PR TITLE
Updates and simplify TEI stylesheet, and test case; validate

### PR DESCRIPTION
**Pull request by brucemiller**
Updated and simplfied TEI stylesheet,  and validated the test case.

Comments and suggestsions from any and all TEI users, or potential ones, welcomed!

(@Thanathan-k ?)

### CODE REVIEW

**Comment by dginev** [comment]
You may also want to tag @physikerwelt since he may have a toolchain using latexml's TEI output to check against this PR.

I don't have much to add myself, if a validator is happy, and the main current TEI consumers are happy, then I'm happy too.

**Comment by physikerwelt** [comment]
@nmeuschke do you know if we have someone currently working on the hyplag / TEI input format, so that we can not only review but also test the change

**Comment by nmeuschke** [comment]
@physikerwelt Unfortunately, nobody is working on math conversion at the moment.

**Comment by brucemiller** [comment]
Thanks for checking, Moritz. I guess we'll go with this for now

**Pull request merged**
