### PR TITLE
New Testing Docker Images

### PR DESCRIPTION
**Pull request by tkw1536**
This PR moves to a new set of docker images with texlive / perl combinations for testing.
These have been cleanly rebuilt from scratch and are more uniform across different versions. 
It also updates the list of versions being tested to include TeXLive 2021.

### CODE REVIEW

**Comment by tkw1536** [comment]
@dginev @brucemiller We should probably discuss this during the meeting later today. 
I just wanted to make the PR so I have something to show for my work over the past week.

**Comment by tkw1536** [comment]
Ready to be merged.

**Comment by tkw1536** [comment]
I've done a bit more research and I've come to the following table.
Comments / Additions welcome, did I forget any distributions?

|  OS / Setup  |  Release   |    EOL    | Perl Version | TeXLive Version |
| ------------ | ---------- | --------- | ------------ | --------------- |
| Fedora 35    | 2021-10    | 2023-11   | 5.34         | 2021            |
| Fedora 34    | 2021-04-27 | 2022-05   | 5.32         | 2020            |
| Fedora 33    | 2020-10-27 | 2021-11   | 5.32         | 2020            |

|  OS / Setup  |  Release   |    EOL    | Perl Version | TeXLive Version |
| ------------ | ---------- | --------- | ------------ | --------------- |
| Debian 11    | 2021-08-14 | 2024      | 5.32         | 2020            |
| Debian 10    | 2019-07-06 | 2022      | 5.28         | 2018            |

|  OS / Setup  |  Release   |    EOL    | Perl Version | TeXLive Version |
| ------------ | ---------- | --------- | ------------ | --------------- |
| Ubuntu 21.10 | 2021-10    | 2022-08   | 5.32         | 2020            |
| Ubuntu 21.04 | 2021-04-22 | 2022-01   | 5.32         | 2020            |
| Ubuntu 20.04 | 2020-04-23 | 2025-04   | 5.30         | 2019            |
| Ubuntu 18.04 | 2018-04-26 | 2023-04   | 5.26         | 2017            |

|  OS / Setup  |  Release   |    EOL    | Perl Version | TeXLive Version |
| ------------ | ---------- | --------- | ------------ | --------------- |
| ArchLinux    | (rolling)  | (rolling) | 5.34         | 2021            |

For future reference:

* [Fedora TeXLive Package](https://src.fedoraproject.org/rpms/texlive)
* [Debian / Ubuntu TeXLive Support](https://www.tug.org/texlive/debian.html)
* [Archlinux TexLive Package](https://archlinux.org/packages/extra/any/texlive-core/)

I'd therefore suggest changing the tested versions to the following versions:
- TeXLive 2021 / Perl 5.34 (Archlinux, Fedora 35)
- TeXLive 2020 / Perl 5.32 (Fedora 33, Fedora 34, Debian 11, Ubuntu 21.04, Ubuntu 21.10)
- TeXLive 2019 / Perl 5.30 (Ubuntu 20.04)
- TeXLive 2018 / Perl 5.28 (Debian 10)
- Perl 5.26, 5.28, 5.30, 5.32, 5.34 without TeXLive

**Comment by tkw1536** [comment]
Versions updated, but [TeXLive 2018 / Perl 5.28](https://github.com/brucemiller/LaTeXML/pull/1590/checks?check_run_id=3257913845#step:7:29) fails the xparse test.

**Comment by tkw1536** [comment]
Rebased onto master, maybe some of the newly merged PRs fixes this.

**Comment by brucemiller** [comment]
Looks like the 2018 case is still failing on `expl3/xparse`

**Comment by tkw1536** [comment]
Yeah, not sure I can do anything about that from my end - is there an issue for this?

**Comment by tkw1536** [comment]
Skipping test on 2018 seems to work. Ready to merge.

**Comment by brucemiller** [comment]
Looks plausible; Thanks!

**Pull request merged**
