### PR TITLE
Add support for unescaped % characters in adsurl

### PR DESCRIPTION
**Pull request by goska**
I have added support for unescaped % characters in adsurl (bug report #710), by adding the code suggested by you (using Semiverbatim) to aa_support.sty.ltxml. It's my first attempt at creating a pull request.

### CODE REVIEW

**Comment by brucemiller** [comment]
Cool! I assume this is standard enough amongst AA folks to include.  But I'm puzzled: Did you test this with the git version or the released one?  I don't think that ```Semiverbatim``` will actually accept ```%```, but you'd need ```Verbatim```.

**Comment by goska** [comment]
I have probably done something irregular. I have made changes to the latest aa_support.sty.ltxml pulled from GitHub, and have tested it with the aa.cls.ltxml (also the latest version pulled from GitHub) and  modified aa_support.sty.ltxml in the same directory as the bib file I was converting, but running an older 0.8.1 installation of LaTeXML from Mac Ports.When I tried using Verbatim, I got a fatal Perl error (I haven't checked if the syntax I used was correct - sorry).

**Comment by brucemiller** [comment]
Exactly: Verbatim wasn't yet defined in 0.8.1, so that gives an error.  OTOH, Semiverbatim in 0.8.1 treats % a normal char, which causes errors *other* places it was used!  So, the current version redefines Semiverbatim to leave % alone, but adds a new Verbatim that neutralizes %.  In summary, we'd like a patch against the current git version, but it won't work with 0.8.1.

**Comment by dginev** [comment]
> but running an older 0.8.1 installation of LaTeXML from Mac Ports

To put it briefly, please always test against the repository head when filing pull requests, to avoid tricky inconsistencies.

And if you're already excited about using latexml enough to be issuing pull requests, switching to a git-based local installation is a great idea anyway.

**Comment by goska** [comment]
OK - thanks. I'll change to Verbatim, but will have to continue to use the other version myself. Switching to the git-based installation locally is not that straightforward for me, as I have to use the 0.8.1 release for my work to be compatible with the production version. But I will install the git-based version on another machine.

**Comment by goska** [comment]
I have replaced Semiverbatim with Verbatim and tested with LaTeXML pulled from GitHub.

**Comment by brucemiller** [comment]
Thanks folks! (I'll reformat & recommit)

**Pull request merged**
