### PR TITLE
use SOURCE_DATE_EPOCH instead of current time

### PR DESCRIPTION
**Pull request by xworld21**
Quick example implementation of SOURCE_DATE_EPOCH (intended to address #1919). Not sure if it is complete. I just grepped "time" and changed modification times in Util::Pack.

The spec asks that LaTeXML "should" throw an error if SOURCE_DATE_EPOCH is set to an invalid value (i.e. not made of just digits) but I don't know where to do it.

I suppose one could refactor `localtime` into a function in some Util module.

### CODE REVIEW

**Comment by xworld21** [comment]
What's missing is generating the EPUB uuid deterministically, but that would mean adding a dependency on Digest or Digest::SHA1. So I'll keep this PR to the minimum and just implement SOURCE_DATE_EPOCH.

**Comment by brucemiller** [comment]
From a TeX perspective, this environment variable seems to come completely out of the blue, although I appreciate the sentiment. It also resonates with #2003, so perhaps there can be a common solution?

**Comment by xworld21** [comment]
Actually pdfTeX and other engines have supported `SOURCE_DATE_EPOCH` for a while, although not always perfectly (the details escape me right now).

Other than that, I agree that a common solution with #2003 would be ideal, e.g. to have a single source of truth for 'current time' which can be overridden via `SOURCE_DATE_EPOCH`, `--timestamp` and/or similar.

**Comment by brucemiller** [comment]
Oh, if it's supported by pdftex, we might as well follow suit for consistency.

**Pull request merged**
