### PR TITLE
Enable VT100 emulation on Windows

### PR DESCRIPTION
**Pull request by xworld21**
~~Tiny~~ small fix to #1572 for Windows.

~~Running `system('')` enables the escape sequences, and disables them on exit, which is the desired behaviour with virtually no work. Also it is completely harmless even if it runs in the wrong terminal.~~ Now based on `Win32::Console`.

I think I did this in the right spot, fenced behind the availability of `Win32::Console` ~~(copied from the similar test from `Util::Pathname`)~~.

It works in both cmd.exe and PowerShell, at least for the versions I have at hand.

### CODE REVIEW

**Comment by dginev** [comment]
Given that this only executes on Windows, that's fine by me. A bit of a shame that we don't have the Windows CI enabled yet, so that the PR gets properly tested, but that time will come soon too...

**Comment by xworld21** [comment]
> Wouldn't have assumed `system('')` would be ever useful for anything in perl.

I wish I could find some documentation about it... fiddling with the console mode itself is too complicated, it requires saving the state and restoring it at the end (or so it seems to me).

**Comment by xworld21** [comment]
Ok, the `system('')` is far too obscure. It works because it launches `cmd.exe /d/x/c`, which happens to set utf-8 and escape sequences, because... why exactly?

I have written a proper implementation with `Win32::Console`. It falls back to `Win32::Console::ANSI` if enabling the VT emulation does not seem to work.

**Comment by dginev** [comment]
Fantastic work, thank you! I think you've dramatically increased the chances of the PR getting merged without the shamanic `system('')` line 😄 Thanks again.

**Comment by brucemiller** [comment]
Wow; the code's scarier, but less mysterious than `system('');`, and is procted by the `eval{ require...`, so seems like it ought to be safe.  Am sure glad we ended up with the `UseSTDERR` as a hook; it seemed unnecessary before, but is really the only sensible place for this kind of special handling.

Emphatic Thanks!

**Pull request merged**
