### PR TITLE
Adjust html header levels in appendix corner cases

### LINKED ISSUE #2167: Header levels off in appendix
After an `\appendix` the resulting header levels are off: both chapters and sections are turned into `<h1>`s. E.g.,
```
\documentclass{book}
\usepackage{latexml}

\begin{document}
\appendix
\chapter{Chapter}
\section{Section}
\paragraph{Paragraph}
\end{document}
```
results in
```
<section class="ltx_appendix">
<h1 class="ltx_title ltx_title_appendix">
<span class="ltx_tag ltx_tag_appendix">Appendix A </span>Chapter</h1>

<section id="S1" class="ltx_section">
<h1 class="ltx_title ltx_title_section">
<span class="ltx_tag ltx_tag_section">A.1 </span>Section</h1>

<section id="S1.SS0.SSS0.Px1" class="ltx_paragraph">
<h2 class="ltx_title ltx_title_paragraph">Paragraph</h2>
```

### PR DESCRIPTION
**Pull request by brucemiller**
fixes #2167

### CODE REVIEW

**Review by dginev — APPROVED** [review]
The adjacent comment strings may also benefit from being updated to remark on the appendix case.

Looks like a nice upgrade.

**Review by dginev — CHANGES_REQUESTED** [review]
Except that this doesn't yet fix #2167 ?

In the minimal example provided the Appendix and Chapter continue to get merged into a single heading, and the chapter element is missing.

I mentioned that in a comment to the issue, e.g. the line:
```xml
    <title><tag close=" ">Appendix A</tag>Chapter</title>
```

The PDF for the example has all 3 of - an appendix, a chapter and a section. The XML seems to have an appendix and a section, missing the chapter? If the `\chapter` is meant to use `ltx:appendix` in this case, shouldn't there be two separate `ltx:appendix` elements?

**Review by dginev — APPROVED** [review]
And yet the final HTML looks correct here. So I guess it's all as intended, just takes "getting used to" on my part.

**Comment by brucemiller** [comment]
`\appendix` doesn't make an appendix, it switches into appendix "mode", 
where (in book), `\chapter` creates an "appendix chapter"

**Comment by dginev** [comment]
Right. LGTM.

**Comment by brucemiller** [comment]
I added some clarifications which prompted a bit clearer coding as well; please re-review.

**Comment by dginev** [comment]
I find the comments are really helpful, thank you for expanding!

I tested with two larger arXiv articles I have locally, as well as with the original reported issue - all converted as expected.

**Review by dginev — APPROVED** [review]
I find the comments are really helpful, thank you for expanding!

I tested with two larger arXiv articles I have locally, as well as with the original reported issue - all converted as expected. LGTM again.

**Pull request merged**
