### PR TITLE
Reformat LaTeXML-maybeMathjax.js and protect local variables with a f…

### PR DESCRIPTION
**Pull request by fred-wang**
…unction closure.

### CODE REVIEW

**Comment by brucemiller** [comment]
Interesting... Is this a more modern way of javascript coding? I'll admit, I'm not that current! :> Any good pointers to Good JS Style, modern practices, etc?

**Comment by fred-wang** [comment]
I guess you are referring to https://en.wikipedia.org/wiki/Immediately-invoked_function_expression
The other changes were more "cosmetic" and based on popular (but subjective) coding style conventions.

**Comment by brucemiller** [comment]
On 08/16/2015 08:17 AM, Frédéric Wang wrote:
> I guess you are referring to
> https://en.wikipedia.org/wiki/Immediately-invoked_function_expression
> The other changes were more "cosmetic" and based on popular (but
> subjective) coding style conventions.

Yeah, it's the iffy bit; mostly the other changes were to
re-indent & un-prefix stuff to accommodate that.

**Comment by brucemiller** [comment]
Oh, forgot to merge! Looks like an appropriate style to adopt. Thanks!!

**Pull request merged**
