### PR TITLE
Post xy cleanup

### PR DESCRIPTION
**Pull request by brucemiller**
As it says, various little bits of cleanup revealed by the arXiv sandbox run.

Ready to merge & re-run the sandbox if you like it.

### CODE REVIEW

**Comment by brucemiller** [comment]
Oh! Could you take a look at Warning/Perl/warn for redefinitions of ams stuff. It appears that when a versioned name is found, it ends up loading amsmath.sty.ltxml even if it's already been loaded, which cases redefinition warnings.

**Comment by brucemiller** [comment]
Nevermind; I think I've got it fixed in the next commit. Some trickery due to file fallback handling.

**Review by dginev — APPROVED** [review]
I was just finishing my coffee preparing to read here when your commit came in - I guess it was lucky I waited :>

From reading through the individual lines, all looks good in my book! LGTM.

(with the usual caveat that some strategic considerations in the alignment code are still beyond my level of understanding, so I'm reading them in a rather shallow manner)

**Comment by brucemiller** [comment]
There's an underlying problem with alignments involving the notion of "empty" cells, and thus empty rows and/or columns. TeX doesn't need the concept; we seemingly do at least by the time we're generating xml or analyzing math structure. Unfortunately, there are 2 problems: you can't prune too early if TeX (or xy) want to access a cell, and secondly I get emptiness wrong often enough (see #1861)

**Pull request merged**
