### PR TITLE
update Mailing list

### PR DESCRIPTION
**Pull request by kohlhase**
it has moved,

### CODE REVIEW

**Comment by dginev** [comment]
Wow, just saw this PR and realized I sent my last list email to the wrong location... explains why it bounced!

**Comment by brucemiller** [comment]
2 questions:  Is "auto" an ignorable file I should know about, or some special .gitignore directive?

And I had the impression that "kwarc"  (and the domain) was moving to erlangen, and services moved servers but not url's... Not complaining, just curious why the change.

**Comment by kohlhase** [comment]
On 15.11.17 15:41, bruce miller wrote:
>
> 2 questions: Is "auto" an ignorable file I should know about, or some
> special .gitignore directive?
>
when I run LaTeX from emacs, it makes a directory "auto" with *.el files
in it, and it bothers me seeing those, feel free to revert this change.
>
> And I had the impression that "kwarc" (and the domain) was moving to
> erlangen, and services moved servers but not url's...
>
yes, that was the plan why we set up mailman on kwarc. But FAU will only
allow a mail server on a domain, if you completely turn it over to them
(i.e. turn over kwarc.info, lists.kwarc.info is not sufficient), and I
was not prepared to do that. Thus the suboptimal transition.
>
> Not complaining, just curious why the change.
>
I am complaining as you see :-).

Michael

**Comment by tkw1536** [comment]
> when I run LaTeX from emacs, it makes a directory "auto" with *.el files in it, and it bothers me seeing those, feel free to revert this change.

Since this is editor specific, and not every LaTeXML contributor uses emacs, it sounds like something that belongs in a [global gitignore](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore).

**Comment by brucemiller** [comment]
LaTeXML contributors that don't use emacs should generally keep quiet about it.

**Comment by dginev** [comment]
> LaTeXML contributors that don't use emacs should generally keep quiet about it.

:no_mouth:

**Comment by brucemiller** [comment]
Thanks!

**Pull request merged**
