### PR TITLE
Hype-compliant readme badges

### PR DESCRIPTION
**Pull request by dginev**
I am now a badge addict. 

You can check how this looks on GitHub by visiting the README on the pushed branch here:
https://github.com/dginev/LaTeXML/blob/modern-badge-showoff/README.pod

You'll make me extremely happy if you decide to merge here, irrational as it is.

### CODE REVIEW

**Comment by dginev** [comment]
I tried to do a refactor using ```=item``` for the individual links in the README, but the POD conversion to HTML is hideous (bold-italic?!). So badges-only for this PR.

**Comment by brucemiller** [comment]
Ah, so you moved them all to the top.  Any chance that inhibits indexing the important keywords (that you wanted :> ) that are closeby?

**Comment by dginev** [comment]
Nope! Nothing is inhibited. The badges are best on the top so that the invoked eye-candy emotions are maximized.

But you also reminded me that I was going to ask you to change the description of the repository which is currently:

> LaTeXML is a TeX and LaTeX to XML translator. http://dlmf.nist.gov/LaTeXML/

to the more indexer-friendly:

> LaTeXML is a TeX and LaTeX to XML/HTML/ePub/MathML converter.  http://dlmf.nist.gov/LaTeXML/

**Comment by dginev** [comment]
Actually, the name is probably redundant in the description, so it may be shortened to:

> A TeX and LaTeX to XML/HTML/ePub/MathML converter. http://dlmf.nist.gov/LaTeXML/

**Comment by brucemiller** [comment]
On 05/31/2016 06:03 PM, Deyan Ginev wrote:
> Actually, the name is probably redundant

A little redundancy can't hurt! :>

**Comment by dginev** [comment]
Woo! :tada: :tada: :tada: 

Now we're talking!

**Pull request merged**
