### PR TITLE
Less restrictive of recursion (usually redundant svg:g)

### PR DESCRIPTION
**Pull request by brucemiller**
Block recursion warnings in a few places where we traverse the XML tree from top-to-bottom, which can be deep, but without cycles.  Also increase the XSLT recursion limit.  These are mostly due to redundant `svg:g` elements, which we'll want to fix, but the results are often acceptable anyway.

Probably will be following up with a couple of semi-related patches.

### CODE REVIEW

**Comment by dginev** [comment]
Looks plausible :>

**Comment by brucemiller** [comment]
Running into some nasty issues processing the bibliography of 2010.15968.  Firstly, there's belt&suspenders handling of the log, so it's really hard to see what's happening within the processing of the bib.  Having savagely hacked that, it appears to be another belt&suspenders with both `includestyles` set, and since the packages declared in PI's are loaded using `preload`, they're getting processed raw, even when the main document didn't ... and in fact, couldn't have.  Just FYI; Gotta take a break from debugging further.

**Comment by brucemiller** [comment]
It makes sense for `preload` from the commandline to be assertive and use `includestyles`, but internally, from `MakeBibliography`, this is pretty severe. Not sure how to distinguish these cases.  Why does `MakeBibliography` (also) enable `includestyles` in the recursive call?

This only affects the one arXiv paper (that I know of), but makes it fatal.

**Comment by brucemiller** [comment]
This should recover a percent; we can deal with the log/includestyles issue later.

**Pull request merged**
