### PR TITLE
Infinite building loop

### PR DESCRIPTION
**Pull request by dginev**
Different take on the now closed #952

### CODE REVIEW

**Comment by brucemiller** [comment]
Yeah, that's what I meant...(& what I did; but if it'll make you happy, I'll accept yours)

**Comment by dginev** [comment]
Always good to land a commit in latexml's master! :+1: 

Wouldn't have minded if you closed and committed it yourself, it's just that you closed the other PR just as I finished the commit, so I filed it in anyway. 

This is a pretty cool fix for the arXiv conversions, could reduce timeouts by a noticeable amount!

**Comment by brucemiller** [comment]
On 02/25/2018 10:31 AM, Deyan Ginev wrote:
> This is a pretty cool fix for the arXiv conversions, could reduce 
> timeouts by a noticeable amount!

That actually happens a lot?

**Comment by dginev** [comment]
It's hard to say, because I don't have good sub-reports for the timeouts. 

http://cortex.mathweb.org/corpus/arXMLiv/tex_to_html/fatal/timeout

Only 1.42% of jobs are reported as timeouts though, so it depends what you mean by "a lot".

**Comment by brucemiller** [comment]
On 02/25/2018 10:35 AM, Deyan Ginev wrote:
> Only 1.42% of jobs are reported as timeouts though, so it depends what 
> you mean by "a lot".

That's a lot... but many are "legit" timeouts!
Maybe...would be cool if most were fixable bugs, though.

**Pull request merged**
