### PR TITLE
Remove class of infinite loop errors during insertion point lookup

### PR DESCRIPTION
**Pull request by dginev**
This PR adds a looping guard to `find_insertion_point` addressing the generic part of #951 

The idea is to recognize cases where we auto-open intermediate nodes that have already been auto-closed during the same recursive chain, and terminate immediately with a malformed error.

The PR reduces the example in #951 to a single second runtime, with the error:
```
Error:malformed:ltx:rect <ltx:rect> loops infinitely when opening an intermediate <ltx:text>
	at /home/dreamweaver/testbed/infinite_loop_latexml_post/nthroot.tex; line 9 col 1
	Currently in XMLDocument[94225025257712]<ltx:document _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b..." _ID_counter_p_="1" xmlns="http://dlmf.nist.gov/LaTeXML">...<ltx:proof _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b...">...<ltx:para _box="LaTeXML::Core::Box=HASH(0x55b2..." _font="Font[serif,medium,upright,10,b..." xml:id="p1">...<ltx:p _box="LaTeXML::Core::Box=HASH(0x55b2..." _font="Font[serif,medium,upright,10,b...">...
	In Core::Document[@0x55b2796bc9b0] at /home/dreamweaver/testbed/infinite_loop_latexml_post/nthroot.tex; line 9 col 1
	 <= Core::Definition::Constructor[\frameb... <= Whatsit[\pic@framebox,Pair[Float[6],F... <= Core::Document[@0x55b2796bc9b0] <= ...
```

and adds the malformed `ltx:rect` directly into its the `ltx:p`.

The main goal here is to have a generic guard that reduces the number of busy loops when converting arXiv, irrespective of the specific schema issue.

### CODE REVIEW

**Comment by brucemiller** [comment]
Part of me wants to not do this 'cause obviously after we fix #951, this kind of thing will *never* happen again! but...

Actually, can' t this be even simpler: You may want to autoclose, then autoopen, but once you've started autoopen, you don't want to autoclose at all; you don't even need to compare tags.

**Comment by dginev** [comment]
Is that simpler or just the inverse of what I did?

**Comment by dginev** [comment]
Ah, you mean have a boolean flag instead of the string comparison, got it. Let me add a commit ...

**Comment by brucemiller** [comment]
Yep, exactly. Actually, I already have it in my `Core::Document` -- it also helps to debug the underlying issue.  But thanks for the inspiration!

**Comment by dginev** [comment]
Hey! Not so fast :> 

At least take a look at my commit, which changes the error to:
```
Error:malformed:ltx:rect <ltx:rect> failed auto-open through <ltx:text> at inadmissible <ltx:text>
```

**Comment by dginev** [comment]
And my commit didn't show because you closed the PR, tsk tsk, now you get a new one :>

**Pull request closed without merging**
