### PR TITLE
test  if ImageMagick policy.xml allows PDF conversion

### LINKED ISSUE #1216: Recent ImageMagick policies induce it broken by default for ghostscript
As can be seen at:
https://stackoverflow.com/a/53180170

And has been experienced by me in all of Authorea, CorTeX conversions of arXiv, and recently working on generic instructions for a latexml-enabled host machine - the modern policy directives of ImageMagick render it quietly disabled on all ghostscript formats. This is very easy to forget when working on the same physical machine for a longer period of time, and "gets me every time" when I setup a new machine that will require image conversions.

The equivalent versioned file for `/etc/ImageMagick-6/policy.xml` needs to be modified from the recent default:
```xml
<!-- disable ghostscript format types -->
  <policy domain="coder" rights="none" pattern="PS" />
  <policy domain="coder" rights="none" pattern="EPS" />
  <policy domain="coder" rights="none" pattern="PDF" />
  <policy domain="coder" rights="none" pattern="XPS" />
```

to the latexml-friendly:
```xml
  <policy domain="coder" rights="read|write" pattern="PS" />
  <policy domain="coder" rights="read|write" pattern="EPS" />
  <policy domain="coder" rights="read|write" pattern="PDF" />
  <policy domain="coder" rights="read|write" pattern="XPS" />
```

An unavoidable side-effect is that this (to an extent) welcomes the security vulnerabilities reported by https://imagetragick.com/ .

I am unsure what the optimal resolution is here - latexml is already "agnostic" to the image processor, and does not require an imagemagick installation, but it is very easy for an end user (even for a co-developer!) to arrive at a setup that "looks good", but is decidedly broken and needs troubleshooting.

Recording here, since I've hit this one too many times now.

### PR DESCRIPTION
**Pull request by dginev**
Fixes #1216 .

The consensus resolution was to try and alert LaTeXML users that the `policy.xml` of ImageMagick needs to be edited for fully featured image conversion.

This PR adds a unit test which detects the situation and warns during `make test`, without treating it as a Failure case, as image conversion is still considered optional. In the case where `Image::Magick` is properly installed and configured, the test checks that the created `PNG` matches an expected size.

Open to suggestions for making both the warning language, as well as the test conditions, more generally useful.

P.S. currently CI will run and skip the test, as we don't install the image-related dependencies.

### CODE REVIEW

**Comment by brucemiller** [comment]
So, the end result of this is that if image magic has the bad policy, you can't even install LaTeXML (from the perspective of the average user)?  Even if you never intend to convert pdf images?

**Comment by dginev** [comment]
As I say in the description:
> This PR adds a unit test which detects the situation and warns during make test, **without treating it as a Failure case**

The test never fails, it only prints a diagnostic message (and succeeds) in the case where the PDF-to-PNG conversion fails, while the dependency was installed.

**Comment by dginev** [comment]
Right, Makefile.PL is a little early (and feels a bit too custom a concern). The testing framework allows a nice abstraction for skipping and diagnostics that felt like a good fit.

And we can also think towards adding more unit testing of image conversion functionality in the long run by just extending that new test file, which felt like a nice bonus...

**Comment by brucemiller** [comment]
Hmm... just did a `git pull`, etc and got
```
t/003_unit_imagemagick.t .. 2/? 
#   Failed test 'PDF to PNG conversion did not produce an image of the expected size'
#   at t/003_unit_imagemagick.t line 23.
#          got: '2457'
#     expected: '2557'
# Looks like you failed 1 test of 2.
t/003_unit_imagemagick.t .. Dubious, test returned 1 (wstat 256, 0x100)
```
which isnt' quite what I was hoping for.

**Pull request merged**
