### PR TITLE
Random robustness fixes

### PR DESCRIPTION
**Pull request by brucemiller**
Random robustness fixes; added some new definitions in LaTeX; more forgiving about registers.

### CODE REVIEW

**Comment by dginev** [comment]
Cool batch!

**Comment by brucemiller** [comment]
Oh; I meant to add; it will read memoit.cls now without errors; at least if you don't do any memoir stuff (your sample file)

**Comment by brucemiller** [comment]
I did randomly check a couple of arXiv articles, hoping that the register fixes would solve some. It mostly doesn't completely solve them, but at least reduces a long cascade of Errors to one. So it's probably not a significant arXiv win, but likely helps cut down the noise. Mostly it was seeing the memoir.cls fail and being surprised that they weren't much worse. For once a "this should be easy" actually was.

**Comment by dginev** [comment]
Might not seem like much to reduce a stream of errors to one, but (provided enough articles are using the missing bits), such gains tend to compound with robustness fixes like these. Each individual patch PR may not be too impactful on its own, but getting 10 to 20 of these little guys positioned may lead to a dramatic improvement in the CorTeX runs, at least in performance, eventually with the % rates.

**Pull request merged**
