### PR TITLE
Suggestion for hinting for maketests

### PR DESCRIPTION
**Pull request by stamer**
Here is one suggestion to provide a hint to compile a testcase. It solves the problem that t/expansion/uflettercase.tex needs xelatex to successfully compile. But maketests tries to either pdftex or pdflatex if called with --pdf option. Use a simple hinting (compatible to llmk) to find out which compiler should be used. 

t/expansion/utflettercase contains `% tex = xelatex`. This is detected and xelatex is used to successfully compile the testcase to pdf. If no hint is given, previous detection for pdflatex is used.

### CODE REVIEW

**Comment by dginev** [comment]
Looks good to me! Thanks!!

**Comment by dginev** [comment]
As an alternative example (not a recommendation, I currently hold no preference myself), I see that the `latexmk` build system uses a variable named `$pdf_mode`, though that is a config parameter, rather than an inline annotation:
https://tex.stackexchange.com/a/501503/78008

**Comment by stamer** [comment]
llmk uses the term latex. Then I thought, well it is not just latex, but tex or pdftex might be candidates as well. Therefore I used `tex = xyz`, but `latex = xyz` is also recognized. I have not a real preference, `pdf_mode` is good. Another option would be to use the term `pdf_command`.

**Comment by brucemiller** [comment]
Exactly, it's not necessarily TeX or LaTeX, but by the same token,
it's not necessarily pdf (although it currently always is). It's about
which TeX "engine" to generate a reality check on the XML.  We want
to emulate xetex or xelatex; someday we may even want to emulate luatex.
That's why I'm thinking in terms of "engine".

Google....
Hmm, it appears that AucTeX recognizes
```
%%% Local Variables:
%%% TeX-engine: pdflatex
%%% End:
```
although it seems that it accepts only specific engines.
(I've never used it)

OTOH, `latexmk` has a variable `$pdf_mode` (set to a number choosing
from a list of commands)

I'd suggest using the `TeX-engine` type of line (w/o bothering
with the Local Variables wrapper.

**Comment by stamer** [comment]
Ok, sounds good, I will take care of that tonight.

**Comment by brucemiller** [comment]
Looks good! This should help enhance tests in the future. Thanks!

**Pull request merged**
