### PR TITLE
ensure intended extensions only in FindFile wrt documentstyle

### PR DESCRIPTION
**Pull request by dginev**
Quick follow-up to #1300 , I did some related testing with:
```tex
\documentstyle[xcolor]{article}
\begin{document}
test \color{red} test.
\end{document}
```

and realized my kpsewhich found `article.sty` in texlive and tried to load it even though I did not provide `--includestyles`. So, patched!

### CODE REVIEW

**Comment by dginev** [comment]
Actually, just one second to test another bit...

**Comment by dginev** [comment]
Ok, my example above, the original arXiv article for aipproc.sty, and now also the following snippet convert nicely:

```tex
\documentstyle[xcolor]{foo}
\begin{document}
test \color{red} test.
\end{document}
```

Where my latest commit made sure the options are handled by OmniBus in cases where the package is "unknown" to latexml for one reason or another. This way the XML produced for the mini doc above is correct, and there isn't even an error - just a single warning that `foo` can not be found.

I also discovered I (once again) got too paranoid with using `withoptions=>1`, it wasn't actually needed when the options hash was passed in at the correct place. So this could be good to merge!

**Comment by brucemiller** [comment]
Travis signed off; quick before dginev changes his mind!

**Comment by dginev** [comment]
Lovely! Getting curious for a partial arXiv run on the latest month this Thursday...

**Pull request merged**
