### PR TITLE
Update CI to use Github Actions

### PR DESCRIPTION
**Pull request by tkw1536**
Previously, the CI tests that were run after every commit used Travis CI. Recent changes introduced a limit on the maximum time a build could run for. LaTeXML easily exceeds this limit.

In order to keep the tests running, this PR moves the tests to GitHub Actions. GitHub Actions is very similar to Travis except that it is offered by GitHub directly and does not have a limit on Open Source projects.

Because of previous work to move the testing environment into a Docker Container, this move does not require many code changes. Furthermore, this does not change which tests are run. In particular the versions of perl and texlive being tested remain the same.

This PR also updates the CI badge in the README. At the moment it 404s, it will start working if this PR is merged.

### CODE REVIEW

**Comment by tkw1536** [comment]
Ok, for some reason the checkmark is showing up on the original commit but not in this PR. 
The CI run for this commit can be found here: https://github.com/tkw1536/LaTeXML/actions/runs/357679141.

**Comment by dginev** [comment]
If this gets us back to unlimited CI quota, two big thumbs up from me!

**Comment by tkw1536** [comment]
Yes it does unless GitHub changes pricing.

**Comment by tkw1536** [comment]
Is there a plan on merging this?

**Comment by dginev** [comment]
I think Bruce is waiting to have no choice but to merge as per usual :> For some interesting reason I ran out of my Travis quota rather quickly in my latexml fork, but it seems the Travis for the main `brucemiller/LaTeXML` never maxed out its quota and kept building. I'm sort of curious why. I'm still all for switching to GH Actions for the unlimited build quota.

**Comment by brucemiller** [comment]
I just put it off till we released, then got sidetracked.  It looks reasonable. Is there any extra config I need to do on the github end, or does it just work?  THANKS!

**Comment by dginev** [comment]
@brucemiller you shouldn't need to do anything else, here is a screenshot of the actions already building with a green checkmark:

image

However, if you get a chance, could you please fix the first line of the README to have all badges next to each other? My OCD was triggered by the new line-break there :>

**Comment by brucemiller** [comment]
I didn't notice that, but the original anchor to travis (containing an 
image) is now replaced by an image without anchor (if you click it you 
get the image!).  Shouldn't there be a link to some "Passing" page?

**Comment by dginev** [comment]
Right, probably best to add a link to the CI actions workflow at:

https://github.com/brucemiller/LaTeXML/actions?query=workflow%3ACI

**Pull request merged**
